apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jc-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    labels: { role: public-node-group }
    instanceType: t2.micro
    desiredCapacity: 2
    privateNetworking: false
  - name: ng-2
    labels: { role: private-node-group }
    instanceType: t2.micro
    desiredCapacity: 2
    privateNetworking: true